/**:
    ros__parameters:
        ## Sensor standard deviation [x,y,z] (optional)
        ## This value is used to override the covariance matrix in nav_msgs/Odometry
        ## Important: Make sure the values provided are in decimal points, or else might give error in execution
        pose_stddev: [0.1, 0.1, 0.0, 0.0, 0.0, 0.1] # [m]
        twist_stddev: [0.01, 0.0, 0.0, 0.0, 0.0, 0.01] # [m/s]
        publish_tf: False
        ## Flasing arguments
        ## Depending on the vehicle, we need certain arguments for the flashing script at bootup. 
        ## The flasing is required to enable the esp.
        ## Examples:
        ## Z39: '' (nano is the default jetson)
        ## F10: 'orin v05' orin is the jetson version and v05 because the piggyboard is v0.5 or higher
        ## Find further information here: https://github.com/zauberzeug/lizard/blob/main/flash.py
        ## In some cases (e.g. F10) we needed a slight delay after flashing the esp. Otherwise the esp did not boot up correctly.
        ## The delay is in seconds and can be set with the sleep_after_flash parameter.
        flashing_arguments: ''
        sleep_after_flash: 0 # seconds

        ## Modules
        ## You can dynamically load the modules that are required. Note that the loaded modules need
        ## to fit to your read data list. Otherwise exceptions will occur. 
        modules:
            - bms_handler
            - estop_handler
            - odom_handler
            - twist_handler
            - yaxis_handler
            - zaxis_handler

        ## Parameter for the twist handler
        twist_handler:
            twist_timeout: 1.0  # [s]   Stop the robot if the cmd_vel is not received for this time
            send_twist_frequency: 20.0  # [hz] Send twist command to esp with this frequency

        read_data:
            list:
                - time
                - linear_speed
                - angular_speed
                - estop1_level
                - estop2_level
                - y_end_l
                - y_end_r
                - y_axis_idle
                - y_axis_position
                - y_alarm_level
                - z_end_t
                - z_end_b
                - z_axis_idle
                - z_axis_position
                - z_alarm_level
            time:
                type: double
                default: 0.0
            linear_speed:
                type: double
                default: 0.0
            angular_speed:
                type: double
                default: 0.0
            estop1_level:
                type: bool
                default: False
            estop2_level:
                type: bool
                default: False
            y_end_l:
                type: double
                default: 0.0
            y_end_r:
                type: double
                default: 0.0
            y_axis_idle:
                type: bool
                default: False
            y_axis_position:
                type: double
                default: 0.0
            y_alarm_level:
                type: bool
                default: False
            z_end_t:
                type: double
                default: 0.0
            z_end_b:
                type: double
                default: 0.0
            z_axis_idle:
                type: bool
                default: False
            z_axis_position:
                type: double
                default: 0.0
            z_alarm_level: 
                type: bool
                default: False